### ISSUE TITLE
Autoclicking SSA checkbox doesn't work

### ISSUE THREAD

**Issue by rdavydov** [K4r0qtuYNE5G4qgZ/RightClickSteamKeyActivator#2]
However, if I open the console and execute:
`document.getElementById('accept_ssa').click();`
it clicks.

Maybe we need to add a delay before these lines:
```
// Click SSA checkbox
document.getElementById('accept_ssa').click();
```
in automate.js?

Like, sleep for 2s and only then click.

**Comment by rdavydov** [comment]
Can confirm that it works with a 2s timeout before click.
Created a [pull request](https://github.com/K4r0qtuYNE5G4qgZ/RightClickSteamKeyActivator/pull/3).

**Comment by rdavydov** [comment]
You're right, I totally forgot about the SteamDB extension! That was the case.
Yeah, changing your code to `.checked = true;` would be awesome, so these extensions will be compatible.

**Comment by rdavydov** [comment]
It is interesting though, why my workaround with the timeout works.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I guess it's simply a timing issue that it didn't work for you and always worked for me.
I now changed it to "checked = true" method and additionally added a fix for timing issues.
But because for me 2 secs are definitely to long, i now did it more flexible.

```
// Check SSA checkbox
var checkSSAExist = setInterval(function CheckSSA() {
const element = document.getElementById( 'accept_ssa' );
if( element )
{
    element.checked = true;
    clearInterval(checkSSAExist);
}
}, 100); // checks every 100ms
```

That way it waits the minium time required.

**Comment by rdavydov** [comment]
Looks perfect now, thank you very much!
Closing.
